### ISSUE TITLE
Instead of frame bounds should be used

### ISSUE THREAD

**Issue by Igor-Palaguta** [Julioacarrettoni/EXPhotoViewer#1]
Instead of imageView.frame here https://github.com/Julioacarrettoni/EXPhotoViewer/blob/master/EXPhotoViewer/EXPhotoViewer.m#L51:

should be used:

self.originalImageRect = [imageView convertRect:imageView.bounds toView:self.view];

**Comment by Julioacarrettoni** [comment]
Thanks! I have been looking for this little bug from quite a time now, I always used images on (0, 0) except for one project where it was at (1, 1) and I noticed something wasn't right but couldn't figure out what :P

Thanks'
