### ISSUE TITLE
addChildViewController instead of storing selfController and parent controller

### ISSUE THREAD

**Issue by Igor-Palaguta** [Julioacarrettoni/EXPhotoViewer#2]
Instead of storing self controller and parent controller you can add self as child to controller where it is presented
https://github.com/Julioacarrettoni/EXPhotoViewer/blob/master/EXPhotoViewer/EXPhotoViewer.m#L64
[ controller addChildViewController: self ];

And then for accessing to parent controller (https://github.com/Julioacarrettoni/EXPhotoViewer/blob/master/EXPhotoViewer/EXPhotoViewer.m#L82) we can user self.parentViewController

**Comment by Julioacarrettoni** [comment]
There is no memory leak and requesting the user to also send the ViewController along with the image will make the Control less easy and flexible to use.
