### ISSUE TITLE
For easier usage better to remove xib

### ISSUE THREAD

**Issue by Igor-Palaguta** [Julioacarrettoni/EXPhotoViewer#3]
We can rewrite xib logic with:

-(void)loadView
{
   self.view = [ [ UIView alloc ] initWithFrame: [ UIScreen mainScreen ].bounds ];
   self.view.backgroundColor = [ UIColor clearColor ];

   UIScrollView\* scrollView = [ [ UIScrollView alloc ] initWithFrame: self.view.bounds ];
   scrollView.maximumZoomScale = 10.f;
   scrollView.minimumZoomScale = 1.f;
   scrollView.delegate = self;
   scrollView.autoresizingMask = UIViewAutoresizingFlexibleWidth | UIViewAutoresizingFlexibleHeight;
   [ self.view addSubview: scrollView ];
   self.zoomeableScrollView = scrollView;

   UIImageView\* imageView = [ [ UIImageView alloc ] initWithFrame: self.view.bounds ];
   [ self.zoomeableScrollView addSubview: imageView ];
   self.theImageView = imageView;
}

And instead of dimView.alpha we can use self.view.backgroundColor = [ UIColor colorWithWhite: alpha: ]

**Comment by Julioacarrettoni** [comment]
I only have three words for you:
"Clap clap clap"

And of course also: "THANK YOU"

I'll review this changes and let you know.

**Comment by Igor-Palaguta** [comment]
podspec and readme still say about xib file
  s.resource  = 'EXPhotoViewer/*.{xib}'
