### ISSUE TITLE
Set custom image for fullscreen, instead of thumbnail.

### ISSUE THREAD

**Issue by TUNER88** [Julioacarrettoni/EXPhotoViewer#6]
Can You add support for providing custom image for fullscreen view?
I my case the thumbnail is to small for fullscreen.

**Comment by brunoalano** [comment]
+1

**Comment by felimuno** [comment]
felimuno/EXPhotoViewer@c9231d89145c594023719e2270eccef00a95e262 i added that new feature on my fork
