### ISSUE TITLE
New tag for Cocoapods

### ISSUE THREAD

**Issue by Bruno-Furtado** [Julioacarrettoni/EXPhotoViewer#8]
@Julioacarrettoni,
You can create a tag to update the version of the project in cocoapods?

**Comment by Julioacarrettoni** [comment]
:+1:

**Comment by Julioacarrettoni** [comment]
Done! tag 1.1.0 Now I just need to check how to properly push an update to cocoapods.

Thanks for mentioning it!

**Comment by BotiKis** [comment]
Still waiting for the pods update. :)

**Comment by Julioacarrettoni** [comment]
:O

SORRY!

I'll do it today :P

**Comment by BotiKis** [comment]
Wow, quick reply. :D
Thanks!

**Comment by Julioacarrettoni** [comment]
I promise I'll do it tomorrow!

**Comment by Julioacarrettoni** [comment]
Closed!
https://github.com/CocoaPods/Specs/pull/11788
